### ISSUE TITLE
The GitHub actions extension gives incorrect feedback / errors

### ISSUE THREAD

**Issue by oodavid** [distributhor/workflow-webhook#50]
The official [GitHub Actions for VSCode](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-github-actions) extension gives errors for a working configuration.

My step looks like this:

```yaml
- name: Trigger Sync Template Webhook
  uses: distributhor/workflow-webhook@v3.0.5
  env:
    webhook_url: ${{ secrets.TEMPLATE_WEBHOOK_URL }}
```

I get this message: `Missing required inputs: 'webhook_url', 'webhook_secret'`

It's worth noting that it says that the `webhook_secret` is a required input, the docs here say otherwise.

My fix is to do this:

```yaml
- name: Trigger Sync Template Webhook
  uses: distributhor/workflow-webhook@v3.0.5
  env:
    webhook_url: ${{ secrets.TEMPLATE_WEBHOOK_URL }}
  # For some reason I get the red wigglies if I don't have this
  # ...they're ignored, and the above variable is actually used
  with:
    webhook_url: unused
    webhook_secret: unused
```

---

The error

<img width="874" alt="Screenshot 2023-10-30 at 10 08 06" src="https://github.com/distributhor/workflow-webhook/assets/46879/4b1b8a34-b35a-43e7-b0bf-22f0a593d508">

**Comment by fenech** [comment]
I think this is because of `webhook_url` and `webhook_secret` being defined as *required* inputs in `action.yml`. So the tooling picks up on the fact that they are missing in the config, and displays an error.

The script in `entrypoint.sh` checks whether a shell variable `$webhook_url` is defined. There is nothing mapping `inputs.webhook_url` to an arg that is passed to the script (as in [this example](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action#creating-an-action-metadata-file)), so the variable is left empty unless it is set via `env`.

So a possible fix would be to pass all the inputs via `args` in `action.yaml`, e.g.
```yaml
runs:
  using: 'docker'
  image: 'docker://ghcr.io/distributhor/workflow-webhook-container:v3.0.5'
  args:
    - ${{ inputs.webhook_url }}
    - ${{ inputs.webhook_secret }}
    - etc.
```

and then referring to them as positional parameters `$1`, `$2` etc. in the entrypoint shell script.
